name: flutter_recipe_app_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
